[tox]
requires =
    tox>4
    virtualenv>20.2
env_list =
    build

[testenv:build]
description = Build package
deps =
    nasdaq-protocols
    build
allowlist_externals =
    nasdaq-ouch-codegen
    nasdaq-itch-codegen
    nasdaq-sqf-codegen
commands =
    nasdaq-ouch-codegen --spec-file=src/nasdaq_protocols_messages/ouch_oe/ouch_oe.xml --app-name=ouch_oe --op-dir=src/nasdaq_protocols_messages/ouch_oe --init-file
    nasdaq-itch-codegen --spec-file=src/nasdaq_protocols_messages/itch_feed/itch_feed.xml --app-name=itch_feed --op-dir=src/nasdaq_protocols_messages/itch_feed --init-file
    nasdaq-sqf-codegen --spec-file=src/nasdaq_protocols_messages/sqf_qe/sqf_qe.xml --app-name=sqf_qe --op-dir=src/nasdaq_protocols_messages/sqf_qe --init-file
    python -m build
